baseurl: https://lyndsayshand.com
title: Lyndsay Shand
author: 
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: img/shand-lyndsay.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: LES
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /aboutme/
      weight: 1
    - name: Publications
      url: /pubs/
      weight: 2
    - name: GitHub
      url: https://github.com/lshand
      weight: 3
   
